{
    "msg": "success",
    "code": 0,
    "data": [
    {
        "menuId": 1,
        "parentId": 0,
        "name": "admin",
        "parentName": null,
        "title": "系统管理",
        "icon": null,
        "jump": null,
        "perms": null,
        "type": 0,
        "orderNum": 0,
        "list": null,
        "spread": null
    },
    {
        "menuId": 3,
        "parentId": 1,
        "name": "menu",
        "parentName": "系统管理",
        "title": "菜单管理",
        "icon": null,
        "jump": "/infoManagement/sys_menu",
        "perms": null,
        "type": 1,
        "orderNum": 1,
        "list": null,
        "spread": null
    },
    {
        "menuId": 4,
        "parentId": 1,
        "name": "role",
        "parentName": "系统管理",
        "title": "角色管理",
        "icon": null,
        "jump": null,
        "perms": null,
        "type": 1,
        "orderNum": 2,
        "list": null,
        "spread": null
    },
    {
        "menuId": 5,
        "parentId": 1,
        "name": "user",
        "parentName": "系统管理",
        "title": "用户管理",
        "icon": null,
        "jump": "/infoManagement/user_info",
        "perms": null,
        "type": 1,
        "orderNum": 3,
        "list": null,
        "spread": null
    },
    {
        "menuId": 6,
        "parentId": 3,
        "name": "list",
        "parentName": "菜单管理",
        "title": "查看",
        "icon": null,
        "jump": null,
        "perms": "sys:menu:list,sys:menu:info",
        "type": 2,
        "orderNum": 0,
        "list": null,
        "spread": null
    },
    {
        "menuId": 7,
        "parentId": 3,
        "name": "add",
        "parentName": "菜单管理",
        "title": "新增",
        "icon": null,
        "jump": null,
        "perms": "sys:menu:save,sys:menu:select",
        "type": 2,
        "orderNum": 1,
        "list": null,
        "spread": null
    },
    {
        "menuId": 8,
        "parentId": 3,
        "name": "update",
        "parentName": "菜单管理",
        "title": "修改",
        "icon": null,
        "jump": null,
        "perms": "sys:menu:update,sys:menu:select",
        "type": 2,
        "orderNum": 2,
        "list": null,
        "spread": null
    },
    {
        "menuId": 9,
        "parentId": 3,
        "name": "delete",
        "parentName": "菜单管理",
        "title": "删除",
        "icon": null,
        "jump": null,
        "perms": "sys:menu:delete",
        "type": 2,
        "orderNum": 3,
        "list": null,
        "spread": null
    },
    {
        "menuId": 10,
        "parentId": 1,
        "name": "customer",
        "parentName": "系统管理",
        "title": "客户管理",
        "icon": null,
        "jump": "/infoManagement/customer_info",
        "perms": "sys:menu:delete",
        "type": 1,
        "orderNum": 4,
        "list": null,
        "spread": null
    },
    {
        "menuId": 11,
        "parentId": 1,
        "name": "supplier",
        "parentName": "系统管理",
        "title": "供应商管理",
        "icon": null,
        "jump": "/infoManagement/supplier_info",
        "perms": "sys:menu:delete",
        "type": 1,
        "orderNum": 5,
        "list": null,
        "spread": null
    }
]
}