
{
    "code": 0
    ,"msg": ""
    ,"data": [{
    "id": "10001"
    ,"username": "Parker000000"
    ,"name": "帕克"
    ,"department": "IT部"
    ,"position": "撸码"
    ,"worknumber": "W8785"
    ,"officephone": "0751-*******"
    ,"skype": "还没有"
    ,"email": "******6@qq.com"
    ,"bankcode": "*****"
    ,"status": "元气满满ya"
    ,"founder": "Parker"
    ,"creattime": "2018-09-12 18:30"
    ,"modifier": "parker"
    ,"edittime": "2018-08-12 18:35"
},{
    "id": "10002"
    ,"username": "Timor"
    ,"name": "提莫"
    ,"department": "市场部"
    ,"position": "丛林巡逻"
    ,"worknumber": "W4585"
    ,"officephone": "0751-*******"
    ,"skype": "还没有"
    ,"email": "******6@qq.com"
    ,"bankcode": "*****"
    ,"status": "提莫队长正在待命"
    ,"founder": "Timor"
    ,"creattime": "2018-09-20 18:30"
    ,"modifier": "Timor"
    ,"edittime": "2018-08-12 18:35"
},{
    "id": "10001"
    ,"username": "Lisin"
    ,"name": "李青"
    ,"department": "研发部"
    ,"position": "撸码"
    ,"worknumber": "W81185"
    ,"officephone": "0751-*******"
    ,"skype": "还没有"
    ,"email": "******6@qq.com"
    ,"bankcode": "*****"
    ,"status": "元气满满ya"
    ,"founder": "Lisin"
    ,"creattime": "2018-09-20 18:00"
    ,"modifier": "Lisin"
    ,"edittime": "2018-08-12 18:35"
}]
}